# デモ録画用の tmux 設定（通常の設定とは分離して使う）
set  -g  status off
set  -g  mouse  off
set  -g  pane-border-status top
set  -g  pane-border-format " #[bold]#{pane_title} "
set  -g  pane-border-style        "fg=colour240"
set  -g  pane-active-border-style "fg=colour39"
set  -g  default-terminal "tmux-256color"
setw -g  automatic-rename off
set  -g  allow-rename off
